### ISSUE TITLE
Why does not support multiple load_time property in a yaml file?

### ISSUE THREAD

**Issue by sungjuly** [coursera/dataduct#72]
If someone wants to make multiple load_time property like this, the dataduct is not supported currently.
I'm just wondering why do you decide to do. If you want to do this, I can contribute this feature.

```
name : test workflow
frequency : daily
load_time: 00:00

steps:
-   step_type: transform
    name: test1
    load_time: 01:00

-   step_type: transform
    name: test2
    load_time: 02:00
```

**Comment by sb2nov** [comment]
In our experience it has generally been useful to keep the pipelines small and simple. So if we want to schedule two things at different times we just create multiple pipelines. The pipeline dependency step helps in creating explicit dependencies if we want.

Originally we started with having a lot of steps in a few pipelines but it turned out to be much harder to maintain in the long run. Happy to share more info so let me know if you have any followups.

**Comment by sungjuly** [comment]
@sb2nov Thank you for sharing experience. It's very meaningful and helpful for me. ;)

**Comment by sungjuly** [comment]
Anyway, I'll contribute this feature when I'm free time. Someone and I need to do this.
